In [5]:
import os
import pandas as pd
import json

# Set the path to the folder containing the JSON files
results_folder = "./results/cap_iqpe_reup_parity"

# Initialize an empty list to store the individual DataFrames
dataframes = []

# Iterate over all files in the results folder
for file in os.listdir(results_folder):
    # Check if the file is a JSON file
    if file.endswith(".json"):
        # Load the JSON file
        file_path = os.path.join(results_folder, file)
        with open(file_path, "r") as f:
            data = json.load(f)
        
        # Convert the JSON data to a Pandas DataFrame and add it to the list
        df = pd.DataFrame(data)
        #df = pd.json_normalize(data)
        dataframes.append(df)

# Combine all individual DataFrames into a single DataFrame
combined_df = pd.concat(dataframes, ignore_index=True)

In [6]:
# Display the combined DataFrame
combined_df

,date,cdevice,time_taken,num_qubits,num_layers,num_reups,omega,Nmin,Nmax,Nstep,num_params_gates,num_params_obs,num_params,num_samples,opt_steps,opt_stop,seed,capacities
0,"27/04/2023, 11:28:41",cpu,325.781856,3,1,1,0.0,1,5,1,7,8,15,5,300,1.000000e-16,0,"[1, 8.277665823727923e-07, 20, 20]"
1,"27/04/2023, 11:28:41",cpu,325.781856,3,1,1,0.0,1,5,1,7,8,15,5,300,1.000000e-16,0,"[2, 7.206783634823295e-07, 20, 40]"
2,"27/04/2023, 11:28:41",cpu,325.781856,3,1,1,0.0,1,5,1,7,8,15,5,300,1.000000e-16,0,"[3, 0.0006059434854942053, 10, 30]"
3,"27/04/2023, 11:55:44",cpu,1337.018741,3,1,1,0.0,1,30,10,7,8,15,10,300,1.000000e-16,0,"[1, 7.004102188264507e-07, 20, 20]"
4,"27/04/2023, 11:55:44",cpu,1337.018741,3,1,1,0.0,1,30,10,7,8,15,10,300,1.000000e-16,0,"[11, 15.491942088628743, 0, 0]"
5,"03/05/2023, 13:03:14",cpu,1356.194991,3,2,2,0.0,10,10,1,22,8,30,10,700,1.000000e-18,0,"[10, 0.3169466555118561, 1, 10]"
6,"03/05/2023, 14:45:10",cpu,1322.401369,3,2,2,0.0,10,10,1,22,8,30,10,700,1.000000e-18,0,"[10, 0.3169466555118561, 1, 10]"