In [1]:
import os
import pandas as pd
import json

# Set the path to the folder containing the JSON files
results_folder = "/home/test/Research/QC/qml-mor/experiments/fat_shattering/results/fat_iqpe_reup_parity"

# Initialize an empty list to store the individual DataFrames
dataframes = []

# Iterate over all files in the results folder
for file in os.listdir(results_folder):
    # Check if the file is a JSON file
    if file.endswith(".json"):
        # Load the JSON file
        file_path = os.path.join(results_folder, file)
        with open(file_path, "r") as f:
            data = json.load(f)
        
        # Convert the JSON data to a Pandas DataFrame and add it to the list
        #df = pd.DataFrame(data)
        df = pd.json_normalize(data)
        dataframes.append(df)

# Combine all individual DataFrames into a single DataFrame
combined_df = pd.concat(dataframes, ignore_index=True)

In [2]:
# Display the combined DataFrame
combined_df

,date,time_taken,cdevice,num_qubits,num_layers,num_reups,omega,dmin,dmax,dstep,...,num_params_gates,num_params_obs,num_params,Sb,Sr,opt_steps,opt_stop,seed,fat_dim,fat_dim_norm
0,"03/05/2023, 13:28:03",82.974862,cpu,3,1,1,0.0,2,2,1,...,7,8,15,10,3,300,1.000000e-16,0,2,0.000277