In [1]:
import os
import pandas as pd
import json

# Set the path to the folder containing the JSON files
results_folder = "./results"

# Initialize an empty list to store the individual DataFrames
dataframes = []

# Iterate over all files in the results folder
for file in os.listdir(results_folder):
    # Check if the file is a JSON file
    if file.endswith(".json"):
        # Load the JSON file
        file_path = os.path.join(results_folder, file)
        with open(file_path, "r") as f:
            data = json.load(f)
        
        # Convert the JSON data to a Pandas DataFrame and add it to the list
        df = pd.DataFrame(data, index=[0])
        #df = pd.json_normalize(data)
        dataframes.append(df)

# Combine all individual DataFrames into a single DataFrame
combined_df = pd.concat(dataframes, ignore_index=True)

In [2]:
combined_df

,date,cdevice,qdevice,shots,model_id,time_taken,num_data_samples,num_parameter_samples,gamma,seed,effdim
0,"19/09/2023, 00:50:00",cpu,default.qubit,None,6,2175.876329,50,10,1.0,0,40.223933
1,"19/09/2023, 00:13:44",cpu,default.qubit,None,5,2142.206723,50,10,1.0,0,40.223933
2,"18/09/2023, 23:38:02",cpu,default.qubit,None,4,2115.000077,50,10,1.0,0,40.985215
3,"18/09/2023, 21:55:11",cpu,default.qubit,None,1,132.042518,50,10,1.0,0,11.333149
4,"18/09/2023, 22:28:37",cpu,default.qubit,None,2,2005.572930,50,10,1.0,0,40.223933
5,"18/09/2023, 23:02:46",cpu,default.qubit,None,3,2049.637128,50,10,1.0,0,40.223933